### ISSUE TITLE
Latest version dons't exists in npm

### ISSUE THREAD

**Issue by arad3455** [WiserSolutions/cypress-antd#14]
0.2.1 is the latest version that was uploaded to npm.
Antd components classes names have been changed since then and version 0.3.2  gives us the best solution :)

**Comment by hon2a** [comment]
@arad3455 For technical reasons, this package is no longer released publicly. Please use [hon2a/cypress-antd](https://github.com/hon2a/cypress-antd).

**Comment by barakcoh** [comment]
thanks @hon2a , it seems Issues are not enabled on hon2a/cypress-antd, so I'm asking here: will you be releasing hon2a/cypress-antd on `npm`? if so, under what name?

**Comment by hon2a** [comment]
@barakcoh I've released it as `@hon2a/cypress-antd` earlier today (version `0.3.2`).

**Comment by arad3455** [comment]
@hon2a  i can see  you have released a new version of `@wisersolutions/cypress-without` as `@hon2a/cypress-without`.
but i can't find  `@hon2a/cypress-antd` in npm at all.

**Comment by hon2a** [comment]
@arad3455 I'm so sorry, I must've gotten confused when trying to publish both quickly, because it turns out I haven't finished re-scoping `@hon2a/cypress-antd` properly. [Here you go.](https://www.npmjs.com/package/@hon2a/cypress-antd)

**Comment by barakcoh** [comment]
Thanks @hon2a for taking the time and care to maintain the library!
