### ISSUE TITLE
Intent to support Ant v4

### ISSUE THREAD

**Issue by jevakallio** [WiserSolutions/cypress-antd#7]
Firstly, thank you for creating and maintaining this project, it seems super useful! 

I'm currently in the process of migrating my company's product to Ant v4, and I've found that our ad-hoc css selector based cypress tests are pretty broken as a result of Antd v4 changing a lot of the components' implementation details. I haven't tried `cypress-antd` against v4 yet, but I'm assuming many of the selectors will be broken for the same reason.

The approach I've decided to take is to use something like `cypress-antd` as we migrate to v4 to encapsulate these implementation details, so we won't find ourselves in the same pit in future version upgrates.

Would you be interested in contributions that add Ant v4 support? I'm asking up front because I don't see an easy way of supporting both simultaneously, so that would be either a breaking change for v3 users, or maintaining two sets of selectors side by side.

**Comment by hon2a** [comment]
@jevakallio Thanks for the interest and offer. Your assumption is correct, the library currently support version 3 of Ant Design. I plan adding (or rather replacing it with) support for v4 as soon as my company is ready to switch over to Ant Design 4. At that point I'm planning to release either a major version or at least another pre-v1 with some clear warning about the breaking changes. Contributions would be welcome, but I can't guarantee a specific release date of the new version as of yet. I'll get back to you when I know more. Of course if the contributions would cover the migration of the current scope over to v4 completely, I'd be happy to release a major version and keep releasing fixes from a branch until we migrate too.

**Comment by jevakallio** [comment]
Okay, thank you! I'll let you know if we end up pursuing this path.
